export enum JobStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum JobType {
  TRANSCRIBE_AUDIO = 'TRANSCRIBE_AUDIO',
  EXTRACT_KNOWLEDGE = 'EXTRACT_KNOWLEDGE',
  GENERATE_RECOMMENDATIONS = 'GENERATE_RECOMMENDATIONS',
  RENDER_SHORT = 'RENDER_SHORT',
  EXPORT_ARTIFACTS = 'EXPORT_ARTIFACTS',
}
